name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build AppImage
      run: ./build_appimage.sh
    - uses: actions/upload-artifact@v4
      with:
        name: pnidgrab.AppImage
        path: ./pnidgrab.AppImage
